apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80
  - name: backend
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer